# Generated by Django 4.2.27 on 2026-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_variants_alter_passwordresettoken_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
