# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_display_order'),
    ]

    operations = [
        # We use AddField but with a condition it might theoretically exist? 
        # No, clean AddField is best for local.
        # For remote where it might exist as NOT NULL, we hope to catch/ignore or we'll assume it doesn't exist.
        # IF this fails on remote, we will know.
        migrations.AddField(
            model_name='product',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
