# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_display_order'),
    ]

    operations = [
        # Similar logic for marketing_cost
        migrations.AddField(
            model_name='product',
            name='marketing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
