# Generated by Django 4.2.27 on 2026-02-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain')], default='cover', max_length=10),
        ),
    ]
