# Generated by Django 4.2.27 on 2026-02-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_image_fit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at']},
        ),
    ]
