# Generated by Django 4.2.27 on 2026-02-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_herobanner_homepagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Cover (Fill)'), ('contain', 'Contain (Fit)'), ('fill', 'Fill (Stretch)'), ('none', 'None (Original Size)')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right')], default='center', max_length=20),
        ),
    ]
