# Generated by Django 4.2.27 on 2026-02-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_herobanner_image_fit_herobanner_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='content_scale',
            field=models.IntegerField(default=100),
        ),
    ]
