# Generated by Django 4.2.27 on 2026-02-26 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_marketingcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='audience_days',
            field=models.IntegerField(default=30, help_text='For recent_signups: users registered within X days'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='audience_type',
            field=models.CharField(choices=[('all_users', 'All Users'), ('ordered_once', 'Ordered At Least Once'), ('never_ordered', 'Never Ordered'), ('recent_signups', 'Recent Signups'), ('abandoned_cart', 'Abandoned Cart'), ('manual', 'Manual Selection')], default='all_users', max_length=30),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='banner_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='batch_size',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('promotional', 'Promotional'), ('abandoned_cart', 'Abandoned Cart'), ('re_engagement', 'Re-engagement'), ('thank_you', 'First Purchase Thank You'), ('upsell', 'Post-purchase Upsell')], default='promotional', max_length=30),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='cta_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='emails_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='emails_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='emails_opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='manual_user_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs for manual selection'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='plain_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='preheader',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='total_recipients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['status'], name='api_marketi_status_df67cb_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['campaign_type'], name='api_marketi_campaig_7575d9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['created_at'], name='api_marketi_created_725608_idx'),
        ),
        migrations.AddField(
            model_name='emaildeliverylog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='api.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='emaildeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['campaign', 'status'], name='api_emailde_campaig_15c7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['user'], name='api_emailde_user_id_251c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['status'], name='api_emailde_status_9ece04_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'user'], name='api_campaig_campaig_ebac10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'user')},
        ),
    ]
