# Generated by Django 4.2.27 on 2026-02-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_campaignrecipient_emaildeliverylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.coupon'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='discount_expiry_days',
            field=models.IntegerField(default=7, help_text='Coupon expires X days after campaign send'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='discount_min_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='discount_usage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
