# Generated by Django 4.2.27 on 2026-02-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_marketingcampaign_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClickLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(max_length=2000)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='api.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('time_to_convert', models.IntegerField(blank=True, help_text='Seconds from click to conversion', null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='api.marketingcampaign')),
                ('click_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emailclicklog')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-converted_at'],
                'indexes': [models.Index(fields=['campaign', 'converted_at'], name='api_emailco_campaig_b85034_idx'), models.Index(fields=['user'], name='api_emailco_user_id_13f88a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailclicklog',
            index=models.Index(fields=['campaign', 'clicked_at'], name='api_emailcl_campaig_6f93f4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclicklog',
            index=models.Index(fields=['user'], name='api_emailcl_user_id_bdc7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclicklog',
            index=models.Index(fields=['converted'], name='api_emailcl_convert_169076_idx'),
        ),
    ]
