# Generated by Django 4.2.27 on 2026-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='earnings_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
