# Generated by Django 4.2.27 on 2026-02-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_blogpost_cover_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image_old',
        ),
    ]
