# Generated by Django 4.2.28 on 2026-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_cart_stockreservation_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_discount_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
