# Generated by Django 4.2.28 on 2026-03-01 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_cart_abandoned_discount_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscribable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_discount_percent',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('interval_days', models.PositiveIntegerField(default=30)),
                ('next_billing_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productvariant')),
            ],
        ),
    ]
