# Generated by Django 4.2.28 on 2026-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_product_is_subscribable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
