# Generated by Django 4.2.28 on 2026-03-03 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_security_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='known_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('order_created', 'Order Created'), ('suspicious_login', 'Suspicious Login (New IP)'), ('role_change', 'Role Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirm'), ('account_lockout', 'Account Lockout')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('source', models.CharField(choices=[('USER', 'User-Triggered'), ('SYSTEM', 'System-Triggered')], default='USER', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx'), models.Index(fields=['severity', 'timestamp'], name='api_auditlo_severit_5c3b20_idx'), models.Index(fields=['ip_address'], name='api_auditlo_ip_addr_5903d9_idx')],
            },
        ),
    ]
